WITH TMP AS ( 
			SELECT *	
				, ROW_NUMBER() OVER(ORDER BY X, Y ASC) AS ID 
			FROM FUNCTIONS )

SELECT DISTINCT TMP1.X, TMP1.Y 
FROM TMP TMP1 
INNER JOIN TMP TMP2 ON TMP1.ID < TMP2.ID 
					AND (TMP1.X = TMP2.Y AND TMP1.Y = TMP2.X);
